import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path
from evaluator.exporter import export_excel, export_pdf

st.set_page_config(page_title="AI Evaluator", layout="wide")
st.title("AI Response Evaluator Dashboard")

DIMS = ["helpfulness", "accuracy", "coherence", "tone", "overall"]

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("Load Results")

    with st.expander("What should the CSV contain?"):
        st.markdown(
            "Upload the file generated by `python main.py` from the `results/` folder. "
            "It must have **exactly these columns**:\n\n"
            "| Column | Type |\n"
            "|--------|------|\n"
            "| `id` | text |\n"
            "| `user_message` | text |\n"
            "| `ai_response` | text |\n"
            "| `helpfulness` | 1–5 |\n"
            "| `accuracy` | 1–5 |\n"
            "| `coherence` | 1–5 |\n"
            "| `tone` | 1–5 |\n"
            "| `overall` | 1–5 |\n"
            "| `reasoning` | text |"
        )

    uploaded_csv = st.file_uploader("Upload eval_results.csv", type="csv")

    if uploaded_csv:
        Path("results").mkdir(exist_ok=True)
        with open("results/eval_results.csv", "wb") as f:
            f.write(uploaded_csv.getbuffer())
        st.success("CSV loaded!")

    st.divider()
    st.info("To generate a fresh CSV, run:\n\n`python main.py`")

# ── Load results ──────────────────────────────────────────────────────────────
results_path = Path("results/eval_results.csv")

if not results_path.exists():
    st.info("No results yet. Upload a CSV from the sidebar or run `python main.py` first.")
    st.stop()

df = pd.read_csv(results_path)
for _dim in DIMS:
    if _dim in df.columns:
        df[_dim] = pd.to_numeric(df[_dim], errors="coerce").fillna(0).astype(int)

expected_cols = ["helpfulness", "accuracy", "coherence", "tone", "overall"]
missing = [c for c in expected_cols if c not in df.columns]
if missing:
    st.error(f"Uploaded CSV is missing columns: {missing}\n\nMake sure you upload the file from your results/ folder.")
    st.stop()

# ── Top metrics ───────────────────────────────────────────────────────────────
st.subheader("Overall Summary")
cols = st.columns(5)
for i, dim in enumerate(DIMS):
    avg = df[dim].mean()
    pass_rate = (df[dim] >= 4).mean() * 100
    cols[i].metric(
        label=dim.capitalize(),
        value=f"{avg:.2f} / 5",
        delta=f"{pass_rate:.0f}% pass rate"
    )

st.divider()

# ── Charts ────────────────────────────────────────────────────────────────────
col1, col2 = st.columns(2)

with col1:
    st.subheader("Score Distribution")
    avg_scores = {dim: df[dim].mean() for dim in DIMS}
    fig = px.bar(
        x=list(avg_scores.keys()),
        y=list(avg_scores.values()),
        color=list(avg_scores.values()),
        color_continuous_scale="teal",
        labels={"x": "Dimension", "y": "Average Score"},
        range_y=[0, 5]
    )
    fig.update_layout(showlegend=False, coloraxis_showscale=False)
    st.plotly_chart(fig, use_container_width=True)

with col2:
    st.subheader("Score Radar")
    avg_vals = [df[dim].mean() for dim in DIMS]
    fig = go.Figure(go.Scatterpolar(
        r=avg_vals,
        theta=[d.capitalize() for d in DIMS],
        fill="toself",
        line_color="#1D9E75"
    ))
    fig.update_layout(polar=dict(radialaxis=dict(range=[0, 5])), showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

st.divider()

# ── Pass / Fail Ratio ─────────────────────────────────────────────────────────
st.subheader("Pass / Fail Ratio")

total_pass = int((df["overall"] >= 4).sum())
total_fail = int((df["overall"] < 4).sum())
pass_rate_pct = total_pass / len(df) * 100 if len(df) > 0 else 0

pf_col1, pf_col2 = st.columns(2)

with pf_col1:
    m1, m2, m3 = st.columns(3)
    m1.metric("Total Pass", total_pass)
    m2.metric("Total Fail", total_fail)
    m3.metric("Pass Rate", f"{pass_rate_pct:.0f}%")

with pf_col2:
    fig_pie = px.pie(
        names=["Pass (>=4)", "Fail (<4)"],
        values=[total_pass, total_fail],
        color=["Pass (>=4)", "Fail (<4)"],
        color_discrete_map={"Pass (>=4)": "#1D9E75", "Fail (<4)": "#E24B4A"},
        hole=0.4,
    )
    fig_pie.update_traces(textposition="inside", textinfo="percent+label")
    fig_pie.update_layout(showlegend=False)
    st.plotly_chart(fig_pie, use_container_width=True)

st.divider()

# ── Results table ─────────────────────────────────────────────────────────────
st.subheader("All Results")

score_filter = st.slider("Filter by minimum overall score", 1, 5, 1)
filtered = df[df["overall"] >= score_filter].copy()
filtered["status"] = filtered["overall"].apply(
    lambda score: "✅ Pass" if score >= 4 else "❌ Fail"
)

display_cols = [c for c in ["id", "status", "user_message", "ai_response"] + DIMS + ["reasoning"] if c in filtered.columns]

st.dataframe(
    filtered[display_cols],
    use_container_width=True,
    height=400,
    column_config={
        dim: st.column_config.ProgressColumn(
            dim.capitalize(),
            min_value=0,
            max_value=5,
            format="%d / 5",
        )
        for dim in DIMS
    },
)

st.divider()

# ── Worst cases ───────────────────────────────────────────────────────────────
st.subheader("Worst Performing Cases")
worst = df.nsmallest(3, "overall")[["id", "user_message", "ai_response", "overall", "reasoning"]]
for _, row in worst.iterrows():
    with st.expander(f"[{row['id']}] Score: {row['overall']}/5 — {str(row['user_message'])[:60]}..."):
        st.write(f"**AI Response:** {row['ai_response']}")
        st.write(f"**Reasoning:** {row['reasoning']}")

st.divider()

# ── Export Reports ────────────────────────────────────────────────────────────
st.subheader("Export Reports")

if "reports_ready" not in st.session_state:
    st.session_state.reports_ready = False

if st.button("Generate Reports"):
    with st.spinner("Generating Excel and PDF reports..."):
        try:
            export_excel("results/eval_results.csv")
            export_pdf("results/eval_results.csv")
            st.session_state.reports_ready = True
            st.success("Reports generated! Download below.")
        except Exception as e:
            st.session_state.reports_ready = False
            st.error(f"Error generating reports: {e}")

if st.session_state.reports_ready:
    dl_col1, dl_col2 = st.columns(2)

    with dl_col1:
        with open("results/eval_report.xlsx", "rb") as f:
            st.download_button(
                label="Download Excel Report",
                data=f,
                file_name="eval_report.xlsx",
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            )

    with dl_col2:
        with open("results/eval_report.pdf", "rb") as f:
            st.download_button(
                label="Download PDF Report",
                data=f,
                file_name="eval_report.pdf",
                mime="application/pdf",
            )